#! /usr/bin/env python

import sys
import subprocess
import os

from ansi2html.converter import Ansi2HTMLConverter



ansiText =  os.path.expanduser('~/Desktop/colorDiff')



proc = subprocess.Popen('git diff HEAD^ HEAD --color',  shell=True, stdout=subprocess.PIPE, stderr = subprocess.PIPE )
diffData = proc.stdout.read()
conv = Ansi2HTMLConverter()

html = conv.convert(diffData)


with open("%s.html" % ansiText, 'w') as wf:
	wf.write(html)

# os.remove(ansiText)
print str(proc.stderr.read()).capitalize()
