#! /usr/bin/env python

import sys
import subprocess
import os

from ansi2html.converter import Ansi2HTMLConverter



ansiText =  os.path.expanduser('~/Desktop/colorDiff')


pr = subprocess.Popen( "git diff HEAD^ HEAD --color > "+ansiText , cwd = os.getcwd() , shell = True, stdout = subprocess.PIPE, stderr = subprocess.PIPE )
(out, error) = pr.communicate()
i = 0
conv = Ansi2HTMLConverter()
html = ''
with open(ansiText, 'r+') as fh:
	for line in fh.read().split("\n"):
		html += conv.convert(line)


with open("%s.html" % ansiText, 'w+') as wf:
	wf.write(html)

os.remove(ansiText)
print str(error).capitalize()
