#! /usr/bin/env python
# -*-coding: utf8-*-
# file: git-maildiff
# command: git maildiff

import sys
from emaildiff import maildiff_cmd as _cmd

if __name__ == '__main__':
	appName = sys.argv[0].split("-")[-1]
	sys.exit(_cmd.main(appName))